"""empty message

Revision ID: 0cf2115faeca
Revises: e433346d9151
Create Date: 2021-01-15 21:08:08.084838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf2115faeca'
down_revision = 'e433346d9151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'title')
    # ### end Alembic commands ###
